### ISSUE TITLE
MORE INFORMATION

### ISSUE THREAD

**Issue by kekko7072** [shaxxx/flutter_usb_write#1]
Hey this plug-in seems to be great for me. I'm working on an APP which need to access data from a USB OTG connected to the phone, in particular i need to read a write them throw the app, the file are in GCODE format, which is the format of 3D printers code, it's like TXT format. Is this plug-in useful to do it on Android? In iOS i'am using the USB's Productor APP but in the future i'd like to do it directly from my app. It will be possible?

**Comment by kekko7072** [comment]
I tried the Example App with an SD CARD Adapter witch support OTG and has an specific app for iOS device, but i cant write nothing to it. Infact the only thing when i try it is reconised as iOS Device and not as the name of the SD card, and also it creates a folder named LOST.DIR where nothing is written, Can you help me and tell me why? This is the link of the adapter [(ADAPTER LINK)](https://it.aliexpress.com/item/4000599386568.html?mb=Q2nw3zYx2MYJoAe&srcSns=WhatsApp&tid=white_backgroup_101&tt=sns_WhatsApp&image=Ub4f4f67cf81e455483ae77e44fc2f529M.jpg&aff_request_id=73b05f17fbce4c9884e866be876902cd-1592411303246-05696-_BSyuGQ&spreadType=socialShare&aff_platform=default&sk=_BSyuGQ&aff_trace_key=73b05f17fbce4c9884e866be876902cd-1592411303246-05696-_BSyuGQ&businessType=ProductDetail&templateId=white_backgroup_101&title=%E2%82%AC+7%2C45++18%25OFF+%7C+4+in+1+lettore+di+Schede+SD+Tf+Card+Reader+%26+USB+C+Adattatore+Micro+SD+Card+per+Computer+iPhone+iPad+galaxy+S8+Android+Mac%2C+micro+USB+3.0&platform=AE&terminal_id=f0f4727e10bc46fcb3bdd19df7550e4b)

**Comment by shaxxx** [comment]
I'm out off office and on my mobile so with limited support. Now, just to make things more clear. There are two layers in usb communication. First that takes care of establishing usb communication channel (negotiate what kind of devices are talking, what can they do, etc...).Second is the protocol used to perform certain action (ie. print, write, send). What you're talking about is the second layer. In USB serial plugin this is serial protocol, you write some command and other side executes it, you dont have to worry about handshakes, negotiation, control and all the other stuff.
With this plugin you send bunch of bytes, there is no second layer implemented.
You would have to know communication protocol for your device ans implement it.
For example, to send string to a esc pos printer you would transform this string in sequence if bytes and send it to printer. But if you need to for example align text to left you would need to send ESC + P + ASCII code 10 (not real commands, just example, I'm writing on my phone) to do that. You would then convert this to a sequence of bytes and send. If you dont know commands to use plugin is useless. You have to know to init printer, tell it that you want it to execute some task and send cobtent to print. This is not trivial. And keep in mind that it's possible that your printer needs two way negotiation this plugin does not support (ie. mobile sends command, printer asks for additional parameters).
I'm afraid you'll have to dive a bit deeper and find out details about the protocol yor printer woeks with.
